//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TORNEOS_FUTBOLEntities : DbContext
    {
        public TORNEOS_FUTBOLEntities()
            : base("name=TORNEOS_FUTBOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contacto> contacto { get; set; }
        public virtual DbSet<equipo> equipo { get; set; }
        public virtual DbSet<genero> genero { get; set; }
        public virtual DbSet<jugador> jugador { get; set; }
        public virtual DbSet<localidad> localidad { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<torneo> torneo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
